### ISSUE TITLE
是否可以剽窃你的代码

### ISSUE THREAD

**Issue by ansjsun** [yida-lxw/ansj_seg#1]
你好.我打算实现ansj lucene5的插件
于是我搜索了下了.

发现你已经完成了这个工作.
因为升级分词可能需要整体我是否可以剽窃下你的代码.
为了保证效率我先剽窃了.如果您反对我这样做.回头我再去修改..感谢你的工作.goodluck

**Comment by yida-lxw** [comment]
我一向都是秉承开源精神，所以只要你也是这样，你可以随意使用我的代码！祝好！

**Comment by ansjsun** [comment]
赞一个

**Comment by ansjsun** [comment]
赞一个 已嫖
